/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          1: 'rgb(var(--violet1) / <alpha-value>)',
          2: 'rgb(var(--violet2) / <alpha-value>)',
          3: 'rgb(var(--violet3) / <alpha-value>)',
          4: 'rgb(var(--violet4) / <alpha-value>)',
          5: 'rgb(var(--violet5) / <alpha-value>)',
          6: 'rgb(var(--violet6) / <alpha-value>)',
          7: 'rgb(var(--violet7) / <alpha-value>)',
          8: 'rgb(var(--violet8) / <alpha-value>)',
          9: 'rgb(var(--violet9) / <alpha-value>)',
          10: 'rgb(var(--violet10) / <alpha-value>)',
          11: 'rgb(var(--violet11) / <alpha-value>)',
          12: 'rgb(var(--violet12) / <alpha-value>)',
        },
        gray: {
          1: 'rgb(var(--mauve1) / <alpha-value>)',
          2: 'rgb(var(--mauve2) / <alpha-value>)',
          3: 'rgb(var(--mauve3) / <alpha-value>)',
          4: 'rgb(var(--mauve4) / <alpha-value>)',
          5: 'rgb(var(--mauve5) / <alpha-value>)',
          6: 'rgb(var(--mauve6) / <alpha-value>)',
          7: 'rgb(var(--mauve7) / <alpha-value>)',
          8: 'rgb(var(--mauve8) / <alpha-value>)',
          9: 'rgb(var(--mauve9) / <alpha-value>)',
          10: 'rgb(var(--mauve10) / <alpha-value>)',
          11: 'rgb(var(--mauve11) / <alpha-value>)',
          12: 'rgb(var(--mauve12) / <alpha-value>)',
        },
        success: {
          1: 'rgb(var(--grass1) / <alpha-value>)',
          2: 'rgb(var(--grass2) / <alpha-value>)',
          3: 'rgb(var(--grass3) / <alpha-value>)',
          4: 'rgb(var(--grass4) / <alpha-value>)',
          5: 'rgb(var(--grass5) / <alpha-value>)',
          6: 'rgb(var(--grass6) / <alpha-value>)',
          7: 'rgb(var(--grass7) / <alpha-value>)',
          8: 'rgb(var(--grass8) / <alpha-value>)',
          9: 'rgb(var(--grass9) / <alpha-value>)',
          10: 'rgb(var(--grass10) / <alpha-value>)',
          11: 'rgb(var(--grass11) / <alpha-value>)',
          12: 'rgb(var(--grass12) / <alpha-value>)',
        },
        warning: {
          1: 'rgb(var(--orange1) / <alpha-value>)',
          2: 'rgb(var(--orange2) / <alpha-value>)',
          3: 'rgb(var(--orange3) / <alpha-value>)',
          4: 'rgb(var(--orange4) / <alpha-value>)',
          5: 'rgb(var(--orange5) / <alpha-value>)',
          6: 'rgb(var(--orange6) / <alpha-value>)',
          7: 'rgb(var(--orange7) / <alpha-value>)',
          8: 'rgb(var(--orange8) / <alpha-value>)',
          9: 'rgb(var(--orange9) / <alpha-value>)',
          10: 'rgb(var(--orange10) / <alpha-value>)',
          11: 'rgb(var(--orange11) / <alpha-value>)',
          12: 'rgb(var(--orange12) / <alpha-value>)',
        },
        danger: {
          1: 'rgb(var(--red1) / <alpha-value>)',
          2: 'rgb(var(--red2) / <alpha-value>)',
          3: 'rgb(var(--red3) / <alpha-value>)',
          4: 'rgb(var(--red4) / <alpha-value>)',
          5: 'rgb(var(--red5) / <alpha-value>)',
          6: 'rgb(var(--red6) / <alpha-value>)',
          7: 'rgb(var(--red7) / <alpha-value>)',
          8: 'rgb(var(--red8) / <alpha-value>)',
          9: 'rgb(var(--red9) / <alpha-value>)',
          10: 'rgb(var(--red10) / <alpha-value>)',
          11: 'rgb(var(--red11) / <alpha-value>)',
          12: 'rgb(var(--red12) / <alpha-value>)',
        },
        info: {
          1: 'rgb(var(--indigo1) / <alpha-value>)',
          2: 'rgb(var(--indigo2) / <alpha-value>)',
          3: 'rgb(var(--indigo3) / <alpha-value>)',
          4: 'rgb(var(--indigo4) / <alpha-value>)',
          5: 'rgb(var(--indigo5) / <alpha-value>)',
          6: 'rgb(var(--indigo6) / <alpha-value>)',
          7: 'rgb(var(--indigo7) / <alpha-value>)',
          8: 'rgb(var(--indigo8) / <alpha-value>)',
          9: 'rgb(var(--indigo9) / <alpha-value>)',
          10: 'rgb(var(--indigo10) / <alpha-value>)',
          11: 'rgb(var(--indigo11) / <alpha-value>)',
          12: 'rgb(var(--indigo12) / <alpha-value>)',
        },
        overlay: {
          'white-1': 'var(--whiteA1)',
          'white-2': 'var(--whiteA2)',
          'white-3': 'var(--whiteA3)',
          'white-4': 'var(--whiteA4)',
          'white-5': 'var(--whiteA5)',
          'white-6': 'var(--whiteA6)',
          'white-7': 'var(--whiteA7)',
          'white-8': 'var(--whiteA8)',
          'white-9': 'var(--whiteA9)',
          'white-10': 'var(--whiteA10)',
          'white-11': 'var(--whiteA11)',
          'white-12': 'var(--whiteA12)',
          'black-1': 'var(--blackA1)',
          'black-2': 'var(--blackA2)',
          'black-3': 'var(--blackA3)',
          'black-4': 'var(--blackA4)',
          'black-5': 'var(--blackA5)',
          'black-6': 'var(--blackA6)',
          'black-7': 'var(--blackA7)',
          'black-8': 'var(--blackA8)',
          'black-9': 'var(--blackA9)',
          'black-10': 'var(--blackA10)',
          'black-11': 'var(--blackA11)',
          'black-12': 'var(--blackA12)',
        },
      },
    },
  },
  corePlugins: {
    aspectRatio: false,
  },
  plugins: [
    require('@tailwindcss/aspect-ratio'),
    require('@tailwindcss/forms'),
    require('@tailwindcss/typography'),
  ],
}
