import type { Client } from 'edgedb'
import { e } from '~/db.server'

const characters = [
	{
		name: 'Albedo',
		region: 'Mondstadt',
		vision: 'Geo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Aloy',
		region: null,
		vision: 'Cryo',
		weapon: 'Bow',
		rarity: 5,
	},
	{
		name: 'Amber',
		region: 'Mondstadt',
		vision: 'Pyro',
		weapon: 'Bow',
		rarity: 4,
	},
	{
		name: 'Arataki Itto',
		region: 'Inazuma',
		vision: 'Geo',
		weapon: 'Claymore',
		rarity: 5,
	},
	{
		name: 'Barbara',
		region: 'Mondstadt',
		vision: 'Hydro',
		weapon: 'Catalyst',
		rarity: 4,
	},
	{
		name: 'Beidou',
		region: 'Liyue',
		vision: 'Electro',
		weapon: 'Claymore',
		rarity: 4,
	},
	{
		name: 'Bennett',
		region: 'Mondstadt',
		vision: 'Pyro',
		weapon: 'Sword',
		rarity: 4,
	},
	{
		name: 'Chongyun',
		region: 'Liyue',
		vision: 'Cryo',
		weapon: 'Claymore',
		rarity: 4,
	},
	{
		name: 'Diluc',
		region: 'Mondstadt',
		vision: 'Pyro',
		weapon: 'Claymore',
		rarity: 5,
	},
	{
		name: 'Diona',
		region: 'Mondstadt',
		vision: 'Cryo',
		weapon: 'Bow',
		rarity: 4,
	},
	{
		name: 'Eula',
		region: 'Mondstadt',
		vision: 'Cryo',
		weapon: 'Claymore',
		rarity: 5,
	},
	{
		name: 'Fischl',
		region: 'Mondstadt',
		vision: 'Electro',
		weapon: 'Bow',
		rarity: 4,
	},
	{
		name: 'Ganyu',
		region: 'Liyue',
		vision: 'Cryo',
		weapon: 'Bow',
		rarity: 5,
	},
	{
		name: 'Gorou',
		region: 'Inazuma',
		vision: 'Geo',
		weapon: 'Bow',
		rarity: 4,
	},
	{
		name: 'Hu Tao',
		region: 'Liyue',
		vision: 'Pyro',
		weapon: 'Polearm',
		rarity: 5,
	},
	{
		name: 'Jean',
		region: 'Mondstadt',
		vision: 'Anemo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Kaedehara Kazuha',
		region: 'Inazuma',
		vision: 'Anemo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Kaeya',
		region: 'Mondstadt',
		vision: 'Cryo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Kamisato Ayaka',
		region: 'Inazuma',
		vision: 'Cryo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Kamisato Ayato',
		region: 'Inazuma',
		vision: 'Hydro',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Keqing',
		region: 'Liyue',
		vision: 'Electro',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Klee',
		region: 'Mondstadt',
		vision: 'Pyro',
		weapon: 'Catalyst',
		rarity: 5,
	},
	{
		name: 'Kujou Sara',
		region: 'Inazuma',
		vision: 'Electro',
		weapon: 'Bow',
		rarity: 4,
	},
	{
		name: 'Kuki Shinobu',
		region: 'Inazuma',
		vision: 'Electro',
		weapon: 'Sword',
		rarity: 4,
	},
	{
		name: 'Lisa',
		region: 'Mondstadt',
		vision: 'Electro',
		weapon: 'Catalyst',
		rarity: 4,
	},
	{
		name: 'Mona',
		region: 'Mondstadt',
		vision: 'Hydro',
		weapon: 'Catalyst',
		rarity: 5,
	},
	{
		name: 'Ningguang',
		region: 'Liyue',
		vision: 'Electro',
		weapon: 'Catalyst',
		rarity: 4,
	},
	{
		name: 'Noelle',
		region: 'Mondstadt',
		vision: 'Geo',
		weapon: 'Claymore',
		rarity: 4,
	},
	{
		name: 'Qiqi',
		region: 'Mondstadt',
		vision: 'Cryo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Raiden Shogun',
		region: 'Inazuma',
		vision: 'Electro',
		weapon: 'Polearm',
		rarity: 5,
	},
	{
		name: 'Razor',
		region: 'Mondstadt',
		vision: 'Electro',
		weapon: 'Claymore',
		rarity: 4,
	},
	{
		name: 'Rosaria',
		region: 'Mondstadt',
		vision: 'Cryo',
		weapon: 'Polearm',
		rarity: 4,
	},
	{
		name: 'Sangonomiya Kokomi',
		region: 'Inazuma',
		vision: 'Hydro',
		weapon: 'Catalyst',
		rarity: 5,
	},
	{
		name: 'Sayu',
		region: 'Inazuma',
		vision: 'Anemo',
		weapon: 'Claymore',
		rarity: 4,
	},
	{
		name: 'Shenhe',
		region: 'Liyue',
		vision: 'Cryo',
		weapon: 'Polearm',
		rarity: 5,
	},
	{
		name: 'Sucrose',
		region: 'Mondstadt',
		vision: 'Anemo',
		weapon: 'Catalyst',
		rarity: 4,
	},
	{
		name: 'Tartaglia',
		region: 'Snezhnaya',
		vision: 'Hydro',
		weapon: 'Bow',
		rarity: 5,
	},
	{
		name: 'Thoma',
		region: 'Inazuma',
		vision: 'Pyro',
		weapon: 'Polearm',
		rarity: 4,
	},
	{
		name: 'Traveler Anemo',
		region: null,
		vision: 'Anemo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Traveler Geo',
		region: null,
		vision: 'Geo',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Traveler Electro',
		region: null,
		vision: 'Electro',
		weapon: 'Sword',
		rarity: 5,
	},
	{
		name: 'Venti',
		region: 'Mondstadt',
		vision: 'Anemo',
		weapon: 'Bow',
		rarity: 5,
	},
	{
		name: 'Xiangling',
		region: 'Liyue',
		vision: 'Pyro',
		weapon: 'Polearm',
		rarity: 4,
	},
	{
		name: 'Xiao',
		region: 'Liyue',
		vision: 'Anemo',
		weapon: 'Polearm',
		rarity: 5,
	},
	{
		name: 'Xingqiu',
		region: 'Liyue',
		vision: 'Hydro',
		weapon: 'Sword',
		rarity: 4,
	},
	{
		name: 'Xinyan',
		region: 'Liyue',
		vision: 'Pyro',
		weapon: 'Claymore',
		rarity: 4,
	},
	{
		name: 'Yae Miko',
		region: 'Inazuma',
		vision: 'Electro',
		weapon: 'Catalyst',
		rarity: 5,
	},
	{
		name: 'Yanfei',
		region: 'Liyue',
		vision: 'Pyro',
		weapon: 'Catalyst',
		rarity: 4,
	},
	{
		name: 'Yelan',
		region: 'Liyue',
		vision: 'Hydro',
		weapon: 'Bow',
		rarity: 5,
	},
	{
		name: 'Yoimiya',
		region: 'Inazuma',
		vision: 'Pyro',
		weapon: 'Bow',
		rarity: 5,
	},
	{
		name: 'Yun Jin',
		region: 'Liyue',
		vision: 'Geo',
		weapon: 'Polearm',
		rarity: 4,
	},
	{
		name: 'Zhongli',
		region: 'Liyue',
		vision: 'Geo',
		weapon: 'Polearm',
		rarity: 5,
	},
]

const queryCharacter = e.params({ characters: e.json }, (params) => {
	return e.for(e.json_array_unpack(params.characters), (c) => {
		return e
			.insert(e.Character, {
				name: e.cast(e.str, c.name),
				region: e.cast(e.Region, c.region),
				vision: e.cast(e.Vision, c.vision),
				weapon: e.cast(e.Weapon, c.weapon),
				rarity: e.cast(e.int16, c.rarity),
			})
			.unlessConflict()
	})
})

export function seedCharacters(client: Client) {
	return queryCharacter.run(client, {
		characters: JSON.stringify(characters),
	})
}
